### ISSUE TITLE
new hyperloglog estimator

### ISSUE THREAD

**Issue by jianshu93** [eric9n/Kun-peng#23]
Hi Kun_peng team,

I think hyperloglogPlus is a very old 64bit version or cardinality/distinct counting algorithm. The most recent hyperloglog estimator should be the improved estimator in this paper: https://arxiv.org/abs/1706.07290, which is more accurate and do not need correction. I would be happy to add it if you think it can be useful.

Thanks,

Jianshu

**Comment by eric9n** [comment]
Here's a suggested English response based on your points:

Thank you for your suggestion and for bringing this paper to our attention. We appreciate your interest in improving Kun_peng.

Regarding the use of HyperLogLog++ in Kun_peng:

1. We use it to estimate the size of the Kun_peng database. For this purpose, we only need a rough estimate, adhering to the principle of "better to overestimate than underestimate."

2. We also use it when processing results to calculate the number of kmers for each taxid. While a higher precision algorithm might positively impact the results, we could alternatively use a hash set for direct calculation without any loss of precision.

For future iterations of Kun_peng, we will certainly consider implementing the improved estimator you've suggested when we encounter relevant estimation scenarios that require higher accuracy.

Thank you again for your valuable input. We're always looking for ways to enhance Kun_peng's performance and accuracy.

**Comment by jianshu93** [comment]
Hi @eric9n,

Yes I agree, the advantage of HLL is not accuracy but space, for any number of sets (N), memory requirement is almost log(N), so very small in a streaming fashion and HLL++ has this property but not accurate enough. Since there is no urgent need to know the exact number of kmers for each taxid (can be several million), I think overall it is good for now. 

Jianshu
