### ISSUE TITLE
macOS compiling error

### ISSUE THREAD

**Issue by jianshu93** [eric9n/Kun-peng#27]
hi @eric9n,

I have no problems on Linux but I always have this compiling error on MacOS (Rust stable channel, 1.80.1) for the most recent commit: 

error[E0284]: type annotations needed
   --> /Users/jianshuzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-middleware-0.3.3/src/client.rs:284:24
    |
284 |             self.inner.poll_ready(cx).map_err(crate::Error::Reqwest)
    |                        ^^^^^^^^^^
    |
    = note: cannot satisfy `<Client as Service<_>>::Error == reqwest::Error`
help: try using a fully qualified path to specify the expected types
    |
284 |             <Client as Service<Request>>::poll_ready(&mut self.inner, cx).map_err(crate::Error::Reqwest)
    |             +++++++++++++++++++++++++++++++++++++++++++++           ~

error[E0283]: type annotations needed
   --> /Users/jianshuzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-middleware-0.3.3/src/client.rs:284:24
    |
284 |             self.inner.poll_ready(cx).map_err(crate::Error::Reqwest)
    |                        ^^^^^^^^^^
    |
    = note: multiple `impl`s satisfying `Client: Service<_>` found in the `reqwest` crate:
            - impl Service<http::Request<Body>> for Client;
            - impl Service<reqwest::Request> for Client;
help: try using a fully qualified path to specify the expected types
    |
284 |             <Client as Service<Request>>::poll_ready(&mut self.inner, cx).map_err(crate::Error::Reqwest)
    |             +++++++++++++++++++++++++++++++++++++++++++++           ~

error[E0284]: type annotations needed
   --> /Users/jianshuzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-middleware-0.3.3/src/client.rs:306:27
    |
306 |             (&self.inner).poll_ready(cx).map_err(crate::Error::Reqwest)
    |                           ^^^^^^^^^^
    |
    = note: cannot satisfy `<&Client as Service<_>>::Error == reqwest::Error`
help: try using a fully qualified path to specify the expected types
    |
306 |             <&Client as Service<Request>>::poll_ready(&mut (&self.inner), cx).map_err(crate::Error::Reqwest)
    |             ++++++++++++++++++++++++++++++++++++++++++++++              ~

error[E0283]: type annotations needed
   --> /Users/jianshuzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-middleware-0.3.3/src/client.rs:306:27
    |
306 |             (&self.inner).poll_ready(cx).map_err(crate::Error::Reqwest)
    |                           ^^^^^^^^^^
    |
    = note: multiple `impl`s satisfying `&Client: Service<_>` found in the `reqwest` crate:
            - impl Service<http::Request<Body>> for &Client;
            - impl Service<reqwest::Request> for &Client;
help: try using a fully qualified path to specify the expected types
    |
306 |             <&Client as Service<Request>>::poll_ready(&mut (&self.inner), cx).map_err(crate::Error::Reqwest)
    |             ++++++++++++++++++++++++++++++++++++++++++++++              ~

Some errors have detailed explanations: E0283, E0284.
For more information about an error, try `rustc --explain E0283`.
error: could not compile `reqwest-middleware` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...

Is that because the reqwest-middleware does not support MacOS? You can try to use cross compiling for aarch64-apple-darwin target

Thanks,

Jianshu

**Comment by eric9n** [comment]
Can you directly download the binary package I placed in the release and run it?

**Comment by eric9n** [comment]
I'll update Rust to version 1.80.1 and give it a try

**Comment by eric9n** [comment]
```
cargo build --target aarch64-apple-darwin
```

```bash
ls -alh target/aarch64-apple-darwin/debug/ncbi_dl
-rwxr-xr-x  1 eric  staff    21M  8 21 09:43 target/aarch64-apple-darwin/debug/ncbi_dl

rustc --version
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

**Comment by jianshu93** [comment]
emm.strange. I will try again.

**Comment by eric9n** [comment]
cargo clean

**Comment by jianshu93** [comment]
There must be something wrong with my Rust environment. Succeeded after completely install everything. 

Thanks,

Jianshu

**Comment by jianshu93** [comment]
It turns out it does happen:

https://github.com/TrueLayer/reqwest-middleware/issues/185

Check this link.

I think updating to the newest version works for me. Please let me know if you can do it or I can do it. 

Thanks,

Jiasnhu

**Comment by eric9n** [comment]
This library mentions potential issues with version 0.12.6. How is this related to version 0.12.4?
